# Assignment 1

![](https://media.giphy.com/media/xT9C25UNTwfZuk85WP/giphy-downsized-large.gif)

Remember the rules of ~Fight~ Code Club:
1. ALWAYS DOCUMENT
2. Cite resources that you use (paste links)
3. Include the names people who you worked with
4. Be neat and organized

## Scrape and Clean data

Based on you proposal, scrape or collect your data:

1. One variable must be either: (40 pts)
    1. scraped from the web OR;
    2. collected from an API AND you must create one new variable that is "new" to the best of your knowledge (combination of other variables representing something new).

2. You must have at least 3 variables, but you may include as many as you want into you final dataset. Likely, you will want to include more to make graphs and regressions. (30pts)

3. You must *be able* to run a regression that makes some sense with this data (the regression doesn't have to be a complete model). Briefly describe one regression you would run with your variables. (**DO NOT** run a regression, yet). (15pts)

4. You must have one combined and cleaned dataset (15 pts)

You must submit one python notebook on how you scraped/gathered data from an api, and how you combined and cleaned you data. I should be able to run your code and reproduce your final data set.  

The other variables that you choose to include do not have to be collected by API or webscraped, but you do have to combine the files and clean the dataset with python.

Thus, you must submit:
- Your finalized data set (only one) (note: you may add more variables in the future).
- Your documented python notebook
- Any associated data files needed to produce the final dataset.

You will be evaluated on:
- Completeness of the data
- Quality of the code 
- The creativity of the new variable/webscraped data you gather

Be sure to upload ALL associated files for your code to run. I will run your code from beginning to end - make it easy for me to replicate your code.

In [ ]:
#I have a new research quesition: "Does fair market rent vary with local vacancy rates?" 
#Basically do citys with high vacany have lower rents and do cities with low vacany have higher rents?
#API Link: https://www.huduser.gov/hudapi/public
# Dependent Variable: Fair Market Rent(fmr_2bed)      Independent Variable: Vacant Apartments(total_vacant)    Controls: Median Income(median_income), Number of Vacent Apartment that are actually available for rent(vacancy_rate)
# Regression Model: FMR_2bed = B0 + B1(total_vacant) + B2(median_income) + B3(vacancy_rate) + e
#My self calculated variable is vacancy_rate which is vacancy_rate = (vacant_for_rent / total_vacant) × 100 <-- this variable basically shows the percent of apartments that are actually available for rent the total_vacant variable just tells us the total number of vacant apartments and this includes apartments that are not for rent
#I think im going to make the vacancy_rate variable my primary Independent Variable becasue I think its better than the total_vacant variable

In [1]:
import requests
import numpy as np
import pandas as pd
import pprint
import time   # to avoid flooding the API

In [2]:
#I made variables out of my API Key and API Link becasue the API Key is long 
API_Key = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI2IiwianRpIjoiNzU5MjE0NGI0ZTFlNWJhZGNhNGRhYjRkN2U1Y2I1YmZjYjY1NjBkYmI5MzA4NzgyYTY2ZTc3YzJlM2NkMzZmYjU2NzJiNzNkYWQ1YWI5ZjkiLCJpYXQiOjE3NzUzMDI2MTIuODY1MjE0LCJuYmYiOjE3NzUzMDI2MTIuODY1MjE4LCJleHAiOjIwOTA5MjE4MTIuODU3NzAxLCJzdWIiOiIxMjQyNjgiLCJzY29wZXMiOltdfQ.CeNgDLRJAbVM5sHzkhkA37C7kBE9FwShYFifYMNHl2hk3zjfMPhCjJxXr0Z3EIjqfQCcil_V6ogPGKXi66h8Hw"

API_URL = "https://www.huduser.gov/hudapi/public" #This is the link to my API

headers = {
    'Authorization': f'Bearer {API_Key}',
    'Mathew'   : 'Assignment 1'   
}

In [3]:
# In this cell I'm creating a list of all 50 states along with DC
#I want to create a list here because then I can loop through all of them and grab the county data I need
all_states = [
    "AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FL",
    "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME",
    "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH",
    "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI",
    "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"
]

print(f"Total states to pull: {len(all_states)}") #Source: https://www.w3schools.com/python/ref_func_len.asp

Total states to pull: 51

In [11]:
#This cell is showing how I got my dependent variable from an API
# Here I am trying to obtain my dependent variable which is fair market rent
# Loop through every state and grab county-level 2-bedroom fair market rent
# fmr_2bed which is is my dependent variable

all_fmr_records = []
failed_states = []

for state in all_states:
    fmr_response = requests.get(
        API_URL + f'/fmr/statedata/{state}',
        headers=headers,
        params={'year': 2023}
    )
    
    if fmr_response.status_code == 200:
        fmr_data = fmr_response.json()
        
        for county in fmr_data['data']['counties']:
            all_fmr_records.append({
                'fips_code' : county.get('fips_code'),
                'county_name': county.get('county_name'),
                'state'     : state,
                'fmr_2bed'  : county.get('Two-Bedroom')   # this is my dependent variable
            })
    else:
        print(f"  ERROR for {state}: status {fmr_response.status_code}")
        failed_states.append(state)
    
    time.sleep(0.5)   

fmr_df = pd.DataFrame(all_fmr_records)

print(f"\nDone! Counties collected: {fmr_df.shape[0]}")
print(f"States that failed: {failed_states if failed_states else 'None'}")
# the API that I am using has fips codes that have extra digits at the end so I trim them to 5 digits to match the Census data I have
fmr_df['fips_code'] = fmr_df['fips_code'].str[:5]
fmr_df.head()

Done! Counties collected: 4680
States that failed: None

  fips_code     county_name state  fmr_2bed
0     01001  Autauga County    AL       977
1     01003  Baldwin County    AL      1206
2     01005  Barbour County    AL       740
3     01007     Bibb County    AL      1075
4     01009   Blount County    AL      1075

In [10]:
# The CSV that I found is from the census the file is in the Assignment 1 folder
# I skipped row 1 because its just a description row
income_raw = pd.read_csv('ACSDT5Y2023.B19013-Data.csv', header=1)

# I am renaming columns here so its easier to read
income_raw.columns = ['geo_id', 'county_name', 'median_income', 'margin_of_error', 'extra']

# This CSV has a GEO ID so I want ot extract the FIPS code from the geo_id column 
income_raw['fips_code'] = income_raw['geo_id'].str[-5:]

# Here I am coverting the median income to numeric
income_raw['median_income'] = pd.to_numeric(income_raw['median_income'], errors='coerce')

# Im just taking the data I need here
income_df = income_raw[['fips_code', 'median_income']].copy() #Source: https://www.w3schools.com/python/pandas/pandas_dataframes.asp
income_df = income_df.dropna(subset=['median_income'])

print(f"Counties with income data: {income_df.shape[0]}")
income_df.head()

Counties with income data: 3220

  fips_code  median_income
0     01001        69841.0
1     01003        75019.0
2     01005        44290.0
3     01007        51215.0
4     01009        61096.0

In [14]:
# The vacancy data that I got is a CSV from the Census and its in the assignment 1 folder
# I'm skipping the first row again because it just has descriptions
vacancy_raw = pd.read_csv('Vacany.csv', header=1)

# Extract only the columns we need
# I'm grabbing columns 0,1,2 and 4 because those are total vacant and vacant for rent
# I'm skipping column 3 because its just the margin of error which I don't need
vacancy_df = vacancy_raw.iloc[:, [0, 1, 2, 4]].copy()
vacancy_df.columns = ['geo_id', 'county_name', 'total_vacant', 'vacant_for_rent']

# I'm doing the same thing here as I did in the last cell and I am getting the 5-digit FIPS code from geo_id
vacancy_df['fips_code'] = vacancy_df['geo_id'].str[-5:] #Source: https://pandas.pydata.org/docs/reference/api/pandas.Series.str.contains.html

# I'm converting the variable to numeric
vacancy_df['total_vacant']    = pd.to_numeric(vacancy_df['total_vacant'],    errors='coerce') #Source: https://pandas.pydata.org/docs/reference/api/pandas.to_numeric.html
vacancy_df['vacant_for_rent'] = pd.to_numeric(vacancy_df['vacant_for_rent'], errors='coerce')

# This is the variable I calculated which is the vacany rate: This variable is the share of vacant units in the county that are actually available for rent
vacancy_df['vacancy_rate'] = vacancy_df['vacant_for_rent'] / vacancy_df['total_vacant']

# Here I am just taking the data I need
vacancy_df = vacancy_df[['fips_code', 'total_vacant', 'vacancy_rate']].copy()
vacancy_df = vacancy_df.dropna(subset=['vacancy_rate']) #Source: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html

print(f"Counties with vacancy data: {vacancy_df.shape[0]}")
vacancy_df.head() #Source: https://www.w3schools.com/python/pandas/ref_df_head.asp

Counties with vacancy data: 3222

  fips_code  total_vacant  vacancy_rate
0     01001          2208      0.095562
1     01003         33876      0.314913
2     01005          2622      0.061785
3     01007          1519      0.092166
4     01009          2816      0.093040

In [16]:
# I am merging all the data from the previous cells and I am matching all this data by the FIPS code
#Source: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html
merged_df = fmr_df.merge(vacancy_df, on='fips_code', how='inner')
merged_df = merged_df.merge(income_df, on='fips_code', how='inner')

# I forgot to turn the vacancy rate variable into a percent so im just correcting that here
merged_df['vacancy_rate'] = merged_df['vacancy_rate'] * 100  

# I am just dropping the missing data here basically all the rows in the dataset that do not have any data
merged_df = merged_df.dropna(subset=['fmr_2bed', 'vacancy_rate', 'median_income', 'total_vacant']) 

# I'm just keeping the columns I want in my final dataset
merged_df = merged_df[['fips_code', 'county_name', 'state', 
                        'fmr_2bed', 'vacancy_rate', 'total_vacant', 'median_income']].copy() #Source: https://www.w3schools.com/python/pandas/ref_df_copy.asp#:~:text=The%20copy()%20method%20returns,be%20reflected%20in%20the%20copy.

#I wanted to do this becasue when I ran it initially I saw that there were more than 4000 counties, but I did some research and found out that theres only 3200 counties in the US so there were probably some counties that go double counted.
merged_df = merged_df.drop_duplicates(subset='fips_code', keep='first')  #Source: https://www.geeksforgeeks.org/pandas/python-pandas-dataframe-drop_duplicates/

print(f"Final dataset: {merged_df.shape[0]} counties across {merged_df['state'].nunique()} states") #source: https://www.geeksforgeeks.org/python/python-pandas-dataframe-nunique/
print("\nColumns:", merged_df.columns.tolist()) #Source: https://stackoverflow.com/questions/19482970/get-a-list-from-pandas-dataframe-column-headers
print("\nDescriptive Statistics:")
merged_df[['fmr_2bed', 'vacancy_rate', 'total_vacant', 'median_income']].describe() #Source: https://stackoverflow.com/questions/73117825/how-do-i-make-a-table-of-descriptive-statistics-for-selected-data-in-python

Final dataset: 3133 counties across 50 states

Columns: ['fips_code', 'county_name', 'state', 'fmr_2bed', 'vacancy_rate', 'total_vacant', 'median_income']

Quick summary:

          fmr_2bed  vacancy_rate   total_vacant  median_income
count  3133.000000   3133.000000    3133.000000    3133.000000
mean    976.452601     11.493582    4702.791574   65994.861794
std     294.793601      9.989805   11543.745787   17338.842908
min     720.000000      0.000000      11.000000   25425.000000
25%     797.000000      3.907638     862.000000   54961.000000
50%     865.000000      8.611670    1790.000000   63636.000000
75%    1030.000000     16.515809    4185.000000   73436.000000
max    3293.000000     59.083986  233830.000000  178707.000000

In [17]:
# The is the end of my project I saved all this data into a csv and it is in the assignment 1 folder
#Source: https://www.geeksforgeeks.org/python/export-pandas-dataframe-to-a-csv-file/
merged_df.to_csv('hud_fmr_vacancy_income_county.csv', index=False)
print("Dataset saved to hud_fmr_vacancy_income_county.csv")
print(f"Number of Rows and Columns: {merged_df.shape}") #I wanted to see how many rows and columns I have

Dataset saved to hud_fmr_vacancy_income_county.csv
Final shape: (3133, 7)